---
title: "Young People Survey Spending Analysis"
date: "January 12, 2019"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(vcd)
library(vcdExtra)
library(logmult)
library(MASS)
library(car)
library(lmtest)
library(moments)
library(ggplot2)
SurveyData <- read.csv('../young-people-survey/SurveyData.csv',header= T)
```

```{r}

str(SurveyData)
table(SurveyData$Internet.usage)
plot(SurveyData$Internet.usage,xlab="Time spent on internet",ylab="Freq")
plot(factor(SurveyData$Entertainment.spending))
plot(factor(SurveyData$Spending.on.looks))
plot(factor(SurveyData$Spending.on.gadgets))
plot(factor(SurveyData$Spending.on.healthy.eating))

SurveyData$Int <- SurveyData$Internet.usage
SurveyData$entertainment <- (SurveyData$Entertainment.spending)
SurveyData$looks <- (SurveyData$Spending.on.looks)
SurveyData$gadgets <- (SurveyData$Spending.on.gadgets)
SurveyData$eating <- (SurveyData$Spending.on.healthy.eating)
SurveyData$Internet.usage <-(as.integer(SurveyData$Internet.usage))


Fed.fit0 <- goodfit(SurveyData$Internet.usage, type="binomial")
Fed.fit1 <- goodfit(SurveyData$Internet.usage, type="poisson")
summary(goodfit(SurveyData$Internet.usage, type="binomial"))
summary(goodfit(SurveyData$Internet.usage, type="poisson"))
distplot(SurveyData$Internet.usage, type="binomial")
distplot(SurveyData$Internet.usage, type="poisson")

## ord_plot shows what distribution to use , in our case it is log-series.
Ord_plot(SurveyData$Internet.usage)



ftable(SurveyData$entertainment)
Ord_plot(SurveyData$entertainment)
summary(goodfit(SurveyData$entertainment, type="binomial"))
#The binomial distribution fits badly
distplot(SurveyData$entertainment, type="binomial")
distplot(SurveyData$entertainment, type="poisson")

ftable(SurveyData$looks)
Ord_plot(SurveyData$looks)
ftable(SurveyData$gadgets)
Ord_plot(SurveyData$gadgets)
ftable(SurveyData$eating)
Ord_plot(SurveyData$eating)


surveyEnt <- ftable(xtabs(~Internet.usage + entertainment, data = SurveyData ))

chisq.test(surveyEnt)
# significant relation between internet usage and entertainment spending

assocstats(surveyEnt)
#By the contingency coefficient, there is moderately strong association between internet usage and entertainment spending

vcd::assoc(surveyEnt, shade=TRUE)

CMHtest(surveyEnt)
#The results of all four tests lead to the same conclusion that there is a significant association between the internet usage and entertainment spending The test for non-zero correlation, treating both variables as ordinal,has the largest ratio of χ2/df.

surveylooks <- ftable(xtabs(~Internet.usage + looks, data = SurveyData ))

chisq.test(surveylooks) # beacuse both are ranked variable
# non significant relation between internet usage and looks spending

assocstats(surveylooks)
#By the contingency coefficient, there is moderately strong association between internet usage and entertainment spending

vcd::assoc(surveylooks, shade=TRUE)

CMHtest(surveylooks)
#The results of  3 tests lead to the same conclusion that there is a significant association between the internet usage and looks spending The test for non-zero correlation, treating both variables as ordinal,has the largest ratio of χ2/df.


surveyGadgets <- ftable(xtabs(~Internet.usage + gadgets, data = SurveyData ))

chisq.test(surveyGadgets)
# significant relation between internet usage and gadgets spending

assocstats(surveyGadgets)
#By the contingency coefficient, there is moderately strong association between internet usage and gadgets spending

vcd::assoc(surveyGadgets, shade=TRUE)

CMHtest(surveyGadgets)


#The results of all four tests lead to the same conclusion that there is a significant association between the internet usage and gadgets spending The test for non-zero correlation, treating both variables as ordinal,has the largest ratio of χ2/df.

surveyEating <- ftable(xtabs(~Internet.usage + eating, data = SurveyData ))

chisq.test(surveyEating)
# non significant relation between internet usage and eating spending

assocstats(surveyEating)
#By the contingency coefficient, there is moderately strong association between internet usage and eating spending

vcd::assoc(surveyEating, shade=TRUE)

CMHtest(surveyEating)
#The results of all four tests lead to the same conclusion that there is a significant association between the internet usage and eating spending The test for non-zero correlation, treating both variables as ordinal,has the largest ratio of χ2/df.

library(ca)
gad_1 <- (xtabs(~SurveyData$Int + gadgets, data = SurveyData ))
op <- par(cex=1.4,mar=c(5,4,2,2)+.1)
gadgets.ca <- ca(gad_1)
res <- plot(gadgets.ca)
par(op)

gad_1 <- (xtabs(~SurveyData$Int + entertainment, data = SurveyData ))
op <- par(cex=1.4,mar=c(5,4,2,2)+.1)
entertainment.ca <- ca(gad_1)
res <- plot(entertainment.ca)
par(op)

## As we have seen the ord_plot shows that slope is positive and intetcept is negative we will use loglm model.
library(MASS)
logModel <- loglm(Internet.usage ~ entertainment + eating + gadgets + looks, data=SurveyData)
summary(logModel)
## Pearson coefficient is high signifying strong relation.

## there is lot of interaction and we are interested in main effects so we will also try to lm.
model1 <- lm(Internet.usage ~ entertainment + eating + gadgets + looks, data = SurveyData, family = "logistic")
summary(model1)
vif(model1)

model2 <- lm(Internet.usage ~ gadgets + looks, data = SurveyData, family = "logistic")
summary(model2)
car::vif(model2)

## so no multicollineraity issue in gadget and looks spending

## spending on eating seems to negatively affected by internet hours.


modelchi <- model1$deviance-model2$deviance
cdf <- model2$df.residual-model1$df.residual
chisqp <- 1 - pchisq(modelchi, cdf)
## no difference in both the models

exp(model2$coefficients)

qqnorm(residuals(model2))
qqline(residuals(model2))
shapiro.test(model2$residuals)

## model does not look good , need to improve

```
## used glm models
```{r}
survey.logistic2 <- glm(Internet.usage ~ gadgets + looks + entertainment + eating,
                      data=SurveyData)

summary(survey.logistic2)
coeftest(survey.logistic2)
car::vif(survey.logistic2)
exp(cbind(OddsRatio=coef(survey.logistic2),
          confint(survey.logistic2)))

qqnorm(residuals(survey.logistic2))
qqline(residuals(survey.logistic2))
shapiro.test(survey.logistic2$residuals)

```

## also trying multinomial model.
```{r}
library("nnet")
test <- multinom(Internet.usage ~ entertainment + eating + gadgets + looks, data = SurveyData)
summary(test)

#summary
#1. Model execution output shows some iteration history and includes the final negative log-likelihood 750.986148. This value is multiplied by two as shown in the model summary as the Residual Deviance.

#2. The summary output has a block of coefficients and another block of standard errors. Each blocks has one row of values corresponding to one model equation. In the block of coefficients, we see that the first row is being compared to Internet.usage = “less than an hour a day” to our baseline Internet.usage = “usage” and the second row to Internet.usage = “most of the day ” to our baseline Internet.usage = “usage” and the third row to Internet.usage = “no time at all ” to our baseline Internet.usage = “usage”

#3. A one-unit increase in entertainment decreases the log odds of being in 'less than an hour a day'  vs. usage  by 0.076

#4. A one-unit increase in entertainment increases the log odds of being in 'most of the day' vs. usage by 0.16

#4. A one-unit increase in entertainment decreases the log odds of being in 'no time at all' vs. usage by 0.57

#Now we’ll calculate Z score and p-Value for the variables in the model.

z <- summary(test)$coefficients/summary(test)$standard.errors
z
p <- (1 - pnorm(abs(z), 0, 1))*2
p
## gadgets looks signficant
exp(coef(test))

head(fitted(test))


qqnorm(residuals(test))
qqline(residuals(test))
shapiro.test(test$residuals)

## little improved
```


## Analysis of spending habit based on demographics.
```{r}
SurveyData$entertainment <- factor(SurveyData$Entertainment.spending)
SurveyData$looks <- factor(SurveyData$Spending.on.looks)
SurveyData$gadgets <- factor(SurveyData$Spending.on.gadgets)
SurveyData$eating <- factor(SurveyData$Spending.on.healthy.eating)

tabulate(SurveyData$Gender)
tabulate(SurveyData$Education)
tabulate(SurveyData$Only.child)
tabulate(SurveyData$Village_town)
tabulate(SurveyData$building)

## all of them are already factored so no need to factor.looks like balanced design
hist.default(SurveyData$Age)


##Now check all possible relationship: 
#age-gender ,age-education , age -only-child ,age-village-town,age-building

model <- aov(SurveyData$Age ~ SurveyData$Gender) 
summary(model)
## it seems significant lets do tukey to see the difference in levels of gender
TukeyHSD(model)
## not significant so not to worry.
model <- aov(SurveyData$Age ~ SurveyData$Only.child) 
summary(model)
## non significant

model <- aov(SurveyData$Age ~ SurveyData$Village_town) 
summary(model)
## non significant
model <- aov(SurveyData$Age ~ SurveyData$building) 
summary(model)
## non significant

## now since there is no multicolliearity we can proceed to model based on spending - lets take it one by one first spending on gadgets
model <- polr(gadgets ~ Gender + Education + Age + Only.child + Village_town + building, data = SurveyData, Hess = TRUE, method = "logistic")
coeftest(model) 


## looks like only building is impacting 

model <- polr(gadgets ~ building, data = SurveyData, Hess = TRUE, method = "logistic")
coeftest(model)

## now since there is no multicolliearity we can proceed to model based on spending - lets take it one by one first spending on entertainment
model <- polr(entertainment ~ Gender + Education + Age + Only.child + Village_town + building, data = SurveyData, Hess = TRUE, method = "logistic")
coeftest(model)

## looks like spending on entertainment is impacted by Only.child,building

## now since there is no multicolliearity we can proceed to model based on spending - lets take it one by one first spending on looks
model <- polr(looks ~ Gender + Education + Age + Only.child + Village_town + building, data = SurveyData, Hess = TRUE, method = "logistic")
coeftest(model)
## looks like spending on looks is impacted by Only.child

## now since there is no multicolliearity we can proceed to model based on spending - lets take it one by one first spending on eating
model <- polr(eating ~ Gender + Education + Age + Only.child + Village_town + building, data = SurveyData, Hess = TRUE, method = "logistic")
coeftest(model)


# ## looks like spending on eating is not impacted by any of them


```

